### ISSUE TITLE
mpv doesn't exist

### ISSUE THREAD

**Issue by sawyerf** [desbma/amg-player#2]
When I try to play a music the application crashes

> [Bandcamp] abandoned-tombs-on-ungodly-grounds: Downloading webpage
[download] Destination: /tmp/amg_8yry2b5c/00001.mp3
[download] 100% of 5.10MiB in 00:04
Traceback (most recent call last):
  File "/usr/bin/amg", line 11, in <module>
    load_entry_point('amg-player==0.4.19', 'console_scripts', 'amg')()
  File "/usr/lib/python3.6/site-packages/amg/__init__.py", line 578, in cl_main
    play(review, track_urls, merge_with_picture=audio_only)
  File "/usr/lib/python3.6/site-packages/amg/__init__.py", line 414, in play
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: 'mpv': 'mpv'

**Comment by desbma** [comment]
You need to install the MPV media player.
